action_repeat: 1
action_scale: 1.0
ang_vel_yaw:
- -1.0
- 1.0
ctrl_dt: 0.02
episode_length: 1000
lin_vel_x:
- -0.5
- 0.5
lin_vel_y:
- -0.8
- 0.8
noise_config:
  level: 0.2
  scales:
    gravity: 0.05
    gyro: 0.2
    joint_pos: 0.03
    joint_vel: 1.5
    linvel: 0.1
push_config:
  enable: true
  interval_range:
  - 5.0
  - 10.0
  magnitude_range:
  - 0.01
  - 0.05
reward_config:
  scales:
    action_rate: -0.01
    alive: 0.5
    ang_vel_xy: -0.1
    feet_air_time: 200.0
    lin_vel_z: -0.2
    orientation: -1.0
    tracking_ang_vel: 0.5
    tracking_lin_vel: 1.0
sim_dt: 0.002
tracking_sigma: 0.25
